[general]
  import = [
    # "~/.config/alacritty/colors-tokyo-night.toml"
    "~/.config/alacritty/colors-catppuccin-mocha.toml",
  ]
[selection]
  save_to_clipboard = true
[window]
  padding = { x = 10, y = 10 }
  dynamic_padding = true
  startup_mode = "Maximized"
  opacity = 0.85
  blur = false
[font]
  normal = { family = "Maple Mono NF CN", style = "Regular" }
  offset = { x = 0, y = 0 }
  size = 12.5
[mouse]
  bindings = [{ mouse = "Right", action = "Paste" }]
[env]
  TERM = "xterm-256color"
