[general]
import = [
    "~/.config/alacritty/colors-catppuccin-mocha.toml"
]
[selection]
    save_to_clipboard = true
[window]
    padding = { x = 10, y = 10 }
    dynamic_padding = true
    startup_mode  = "Maximized"
    opacity = 0.95
    blur = true
[font]
    normal = { family = "CaskaydiaMono Nerd Font", style="Regular"}
    offset = { x = 0, y = 0 }
    size = 13.5
[mouse]
    bindings = [
        { mouse = "Right", action = "Paste" },
    ]
